// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViadexDashboard.Data;

#nullable disable

namespace ViadexDashboard.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ViadexDashboard.Models.Compliance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<bool>("EncryptionEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("PolicyCompliant")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("ComplianceData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeviceId = 1,
                            EncryptionEnabled = true,
                            PolicyCompliant = false
                        },
                        new
                        {
                            Id = 2,
                            DeviceId = 2,
                            EncryptionEnabled = true,
                            PolicyCompliant = true
                        },
                        new
                        {
                            Id = 3,
                            DeviceId = 3,
                            EncryptionEnabled = false,
                            PolicyCompliant = false
                        },
                        new
                        {
                            Id = 4,
                            DeviceId = 4,
                            EncryptionEnabled = true,
                            PolicyCompliant = false
                        },
                        new
                        {
                            Id = 5,
                            DeviceId = 5,
                            EncryptionEnabled = false,
                            PolicyCompliant = true
                        },
                        new
                        {
                            Id = 6,
                            DeviceId = 6,
                            EncryptionEnabled = true,
                            PolicyCompliant = true
                        },
                        new
                        {
                            Id = 7,
                            DeviceId = 7,
                            EncryptionEnabled = true,
                            PolicyCompliant = true
                        },
                        new
                        {
                            Id = 8,
                            DeviceId = 8,
                            EncryptionEnabled = false,
                            PolicyCompliant = false
                        },
                        new
                        {
                            Id = 9,
                            DeviceId = 9,
                            EncryptionEnabled = true,
                            PolicyCompliant = false
                        },
                        new
                        {
                            Id = 10,
                            DeviceId = 10,
                            EncryptionEnabled = true,
                            PolicyCompliant = false
                        },
                        new
                        {
                            Id = 11,
                            DeviceId = 11,
                            EncryptionEnabled = true,
                            PolicyCompliant = true
                        },
                        new
                        {
                            Id = 12,
                            DeviceId = 12,
                            EncryptionEnabled = true,
                            PolicyCompliant = true
                        },
                        new
                        {
                            Id = 13,
                            DeviceId = 13,
                            EncryptionEnabled = true,
                            PolicyCompliant = true
                        },
                        new
                        {
                            Id = 14,
                            DeviceId = 14,
                            EncryptionEnabled = false,
                            PolicyCompliant = false
                        },
                        new
                        {
                            Id = 15,
                            DeviceId = 15,
                            EncryptionEnabled = false,
                            PolicyCompliant = true
                        },
                        new
                        {
                            Id = 16,
                            DeviceId = 16,
                            EncryptionEnabled = true,
                            PolicyCompliant = true
                        },
                        new
                        {
                            Id = 17,
                            DeviceId = 17,
                            EncryptionEnabled = true,
                            PolicyCompliant = true
                        },
                        new
                        {
                            Id = 18,
                            DeviceId = 18,
                            EncryptionEnabled = false,
                            PolicyCompliant = false
                        },
                        new
                        {
                            Id = 19,
                            DeviceId = 19,
                            EncryptionEnabled = true,
                            PolicyCompliant = false
                        },
                        new
                        {
                            Id = 20,
                            DeviceId = 20,
                            EncryptionEnabled = true,
                            PolicyCompliant = true
                        },
                        new
                        {
                            Id = 21,
                            DeviceId = 21,
                            EncryptionEnabled = true,
                            PolicyCompliant = false
                        },
                        new
                        {
                            Id = 22,
                            DeviceId = 22,
                            EncryptionEnabled = true,
                            PolicyCompliant = false
                        },
                        new
                        {
                            Id = 23,
                            DeviceId = 23,
                            EncryptionEnabled = true,
                            PolicyCompliant = true
                        },
                        new
                        {
                            Id = 24,
                            DeviceId = 24,
                            EncryptionEnabled = true,
                            PolicyCompliant = true
                        },
                        new
                        {
                            Id = 25,
                            DeviceId = 25,
                            EncryptionEnabled = true,
                            PolicyCompliant = true
                        });
                });

            modelBuilder.Entity("ViadexDashboard.Models.DEXScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<double>("PerformanceScore")
                        .HasColumnType("float");

                    b.Property<double>("UserFeedbackScore")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("DEXScores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeviceId = 1,
                            PerformanceScore = 85.0,
                            UserFeedbackScore = 4.2000000000000002
                        },
                        new
                        {
                            Id = 2,
                            DeviceId = 2,
                            PerformanceScore = 90.299999999999997,
                            UserFeedbackScore = 4.5
                        },
                        new
                        {
                            Id = 3,
                            DeviceId = 3,
                            PerformanceScore = 78.5,
                            UserFeedbackScore = 3.8999999999999999
                        },
                        new
                        {
                            Id = 4,
                            DeviceId = 4,
                            PerformanceScore = 88.099999999999994,
                            UserFeedbackScore = 4.2999999999999998
                        },
                        new
                        {
                            Id = 5,
                            DeviceId = 5,
                            PerformanceScore = 92.400000000000006,
                            UserFeedbackScore = 4.7000000000000002
                        },
                        new
                        {
                            Id = 6,
                            DeviceId = 6,
                            PerformanceScore = 80.200000000000003,
                            UserFeedbackScore = 4.0
                        },
                        new
                        {
                            Id = 7,
                            DeviceId = 7,
                            PerformanceScore = 83.599999999999994,
                            UserFeedbackScore = 4.0999999999999996
                        },
                        new
                        {
                            Id = 8,
                            DeviceId = 8,
                            PerformanceScore = 87.900000000000006,
                            UserFeedbackScore = 4.4000000000000004
                        },
                        new
                        {
                            Id = 9,
                            DeviceId = 9,
                            PerformanceScore = 91.5,
                            UserFeedbackScore = 4.5999999999999996
                        },
                        new
                        {
                            Id = 10,
                            DeviceId = 10,
                            PerformanceScore = 76.799999999999997,
                            UserFeedbackScore = 3.7999999999999998
                        },
                        new
                        {
                            Id = 11,
                            DeviceId = 11,
                            PerformanceScore = 85.700000000000003,
                            UserFeedbackScore = 4.2000000000000002
                        },
                        new
                        {
                            Id = 12,
                            DeviceId = 12,
                            PerformanceScore = 89.200000000000003,
                            UserFeedbackScore = 4.2999999999999998
                        },
                        new
                        {
                            Id = 13,
                            DeviceId = 13,
                            PerformanceScore = 93.099999999999994,
                            UserFeedbackScore = 4.7999999999999998
                        },
                        new
                        {
                            Id = 14,
                            DeviceId = 14,
                            PerformanceScore = 79.400000000000006,
                            UserFeedbackScore = 3.8999999999999999
                        },
                        new
                        {
                            Id = 15,
                            DeviceId = 15,
                            PerformanceScore = 86.299999999999997,
                            UserFeedbackScore = 4.2000000000000002
                        },
                        new
                        {
                            Id = 16,
                            DeviceId = 16,
                            PerformanceScore = 90.0,
                            UserFeedbackScore = 4.5
                        },
                        new
                        {
                            Id = 17,
                            DeviceId = 17,
                            PerformanceScore = 81.700000000000003,
                            UserFeedbackScore = 4.0
                        },
                        new
                        {
                            Id = 18,
                            DeviceId = 18,
                            PerformanceScore = 84.5,
                            UserFeedbackScore = 4.0999999999999996
                        },
                        new
                        {
                            Id = 19,
                            DeviceId = 19,
                            PerformanceScore = 88.799999999999997,
                            UserFeedbackScore = 4.4000000000000004
                        },
                        new
                        {
                            Id = 20,
                            DeviceId = 20,
                            PerformanceScore = 75.900000000000006,
                            UserFeedbackScore = 3.7000000000000002
                        },
                        new
                        {
                            Id = 21,
                            DeviceId = 21,
                            PerformanceScore = 82.599999999999994,
                            UserFeedbackScore = 4.0
                        },
                        new
                        {
                            Id = 22,
                            DeviceId = 22,
                            PerformanceScore = 87.200000000000003,
                            UserFeedbackScore = 4.2999999999999998
                        },
                        new
                        {
                            Id = 23,
                            DeviceId = 23,
                            PerformanceScore = 92.0,
                            UserFeedbackScore = 4.5999999999999996
                        },
                        new
                        {
                            Id = 24,
                            DeviceId = 24,
                            PerformanceScore = 77.5,
                            UserFeedbackScore = 3.7999999999999998
                        },
                        new
                        {
                            Id = 25,
                            DeviceId = 25,
                            PerformanceScore = 89.700000000000003,
                            UserFeedbackScore = 4.4000000000000004
                        });
                });

            modelBuilder.Entity("ViadexDashboard.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Laptop1",
                            OS = "Windows 10",
                            SerialNumber = "SN001"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Laptop2",
                            OS = "Windows 11",
                            SerialNumber = "SN002"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Laptop3",
                            OS = "Windows 10",
                            SerialNumber = "SN003"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Laptop4",
                            OS = "Windows 11",
                            SerialNumber = "SN004"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Laptop5",
                            OS = "Windows 10",
                            SerialNumber = "SN005"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Laptop6",
                            OS = "Windows 11",
                            SerialNumber = "SN006"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Laptop7",
                            OS = "Windows 10",
                            SerialNumber = "SN007"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Laptop8",
                            OS = "Windows 11",
                            SerialNumber = "SN008"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Laptop9",
                            OS = "Windows 10",
                            SerialNumber = "SN009"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Laptop10",
                            OS = "Windows 11",
                            SerialNumber = "SN010"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Laptop11",
                            OS = "Windows 10",
                            SerialNumber = "SN011"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Laptop12",
                            OS = "Windows 11",
                            SerialNumber = "SN012"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Laptop13",
                            OS = "Windows 10",
                            SerialNumber = "SN013"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Laptop14",
                            OS = "Windows 11",
                            SerialNumber = "SN014"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Laptop15",
                            OS = "Windows 10",
                            SerialNumber = "SN015"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Laptop16",
                            OS = "Windows 11",
                            SerialNumber = "SN016"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Laptop17",
                            OS = "Windows 10",
                            SerialNumber = "SN017"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Laptop18",
                            OS = "Windows 11",
                            SerialNumber = "SN018"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Laptop19",
                            OS = "Windows 10",
                            SerialNumber = "SN019"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Laptop20",
                            OS = "Windows 11",
                            SerialNumber = "SN020"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Laptop21",
                            OS = "Windows 10",
                            SerialNumber = "SN021"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Laptop22",
                            OS = "Windows 11",
                            SerialNumber = "SN022"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Laptop23",
                            OS = "Windows 10",
                            SerialNumber = "SN023"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Laptop24",
                            OS = "Windows 11",
                            SerialNumber = "SN024"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Laptop25",
                            OS = "Windows 10",
                            SerialNumber = "SN025"
                        });
                });

            modelBuilder.Entity("ViadexDashboard.Models.Sustainability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CarbonFootprint")
                        .HasColumnType("float");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<double>("PowerConsumption")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("SustainabilityData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarbonFootprint = 10.199999999999999,
                            DeviceId = 1,
                            PowerConsumption = 50.5
                        },
                        new
                        {
                            Id = 2,
                            CarbonFootprint = 9.8000000000000007,
                            DeviceId = 2,
                            PowerConsumption = 45.299999999999997
                        },
                        new
                        {
                            Id = 3,
                            CarbonFootprint = 11.0,
                            DeviceId = 3,
                            PowerConsumption = 52.100000000000001
                        },
                        new
                        {
                            Id = 4,
                            CarbonFootprint = 10.5,
                            DeviceId = 4,
                            PowerConsumption = 48.700000000000003
                        },
                        new
                        {
                            Id = 5,
                            CarbonFootprint = 9.9000000000000004,
                            DeviceId = 5,
                            PowerConsumption = 47.200000000000003
                        },
                        new
                        {
                            Id = 6,
                            CarbonFootprint = 10.6,
                            DeviceId = 6,
                            PowerConsumption = 49.799999999999997
                        },
                        new
                        {
                            Id = 7,
                            CarbonFootprint = 11.4,
                            DeviceId = 7,
                            PowerConsumption = 53.5
                        },
                        new
                        {
                            Id = 8,
                            CarbonFootprint = 9.6999999999999993,
                            DeviceId = 8,
                            PowerConsumption = 46.899999999999999
                        },
                        new
                        {
                            Id = 9,
                            CarbonFootprint = 10.9,
                            DeviceId = 9,
                            PowerConsumption = 51.0
                        },
                        new
                        {
                            Id = 10,
                            CarbonFootprint = 10.300000000000001,
                            DeviceId = 10,
                            PowerConsumption = 50.200000000000003
                        },
                        new
                        {
                            Id = 11,
                            CarbonFootprint = 10.0,
                            DeviceId = 11,
                            PowerConsumption = 48.0
                        },
                        new
                        {
                            Id = 12,
                            CarbonFootprint = 9.5999999999999996,
                            DeviceId = 12,
                            PowerConsumption = 45.700000000000003
                        },
                        new
                        {
                            Id = 13,
                            CarbonFootprint = 11.800000000000001,
                            DeviceId = 13,
                            PowerConsumption = 54.200000000000003
                        },
                        new
                        {
                            Id = 14,
                            CarbonFootprint = 9.8000000000000007,
                            DeviceId = 14,
                            PowerConsumption = 47.5
                        },
                        new
                        {
                            Id = 15,
                            CarbonFootprint = 10.699999999999999,
                            DeviceId = 15,
                            PowerConsumption = 50.899999999999999
                        },
                        new
                        {
                            Id = 16,
                            CarbonFootprint = 10.4,
                            DeviceId = 16,
                            PowerConsumption = 49.399999999999999
                        },
                        new
                        {
                            Id = 17,
                            CarbonFootprint = 11.199999999999999,
                            DeviceId = 17,
                            PowerConsumption = 52.799999999999997
                        },
                        new
                        {
                            Id = 18,
                            CarbonFootprint = 10.1,
                            DeviceId = 18,
                            PowerConsumption = 48.299999999999997
                        },
                        new
                        {
                            Id = 19,
                            CarbonFootprint = 9.6999999999999993,
                            DeviceId = 19,
                            PowerConsumption = 47.0
                        },
                        new
                        {
                            Id = 20,
                            CarbonFootprint = 10.6,
                            DeviceId = 20,
                            PowerConsumption = 50.700000000000003
                        },
                        new
                        {
                            Id = 21,
                            CarbonFootprint = 9.5,
                            DeviceId = 21,
                            PowerConsumption = 46.5
                        },
                        new
                        {
                            Id = 22,
                            CarbonFootprint = 10.800000000000001,
                            DeviceId = 22,
                            PowerConsumption = 51.299999999999997
                        },
                        new
                        {
                            Id = 23,
                            CarbonFootprint = 10.5,
                            DeviceId = 23,
                            PowerConsumption = 49.899999999999999
                        },
                        new
                        {
                            Id = 24,
                            CarbonFootprint = 11.1,
                            DeviceId = 24,
                            PowerConsumption = 53.0
                        },
                        new
                        {
                            Id = 25,
                            CarbonFootprint = 10.199999999999999,
                            DeviceId = 25,
                            PowerConsumption = 48.600000000000001
                        });
                });

            modelBuilder.Entity("ViadexDashboard.Models.Telemetry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CPUUsage")
                        .HasColumnType("float");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<double>("DiskUsage")
                        .HasColumnType("float");

                    b.Property<double>("MemoryUsage")
                        .HasColumnType("float");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("TelemetryData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CPUUsage = 25.5,
                            DeviceId = 1,
                            DiskUsage = 45.100000000000001,
                            MemoryUsage = 35.200000000000003,
                            RecordedAt = new DateTime(2024, 1, 1, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CPUUsage = 22.300000000000001,
                            DeviceId = 2,
                            DiskUsage = 48.5,
                            MemoryUsage = 32.799999999999997,
                            RecordedAt = new DateTime(2024, 1, 2, 11, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CPUUsage = 30.100000000000001,
                            DeviceId = 3,
                            DiskUsage = 50.299999999999997,
                            MemoryUsage = 40.700000000000003,
                            RecordedAt = new DateTime(2024, 1, 3, 9, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CPUUsage = 28.399999999999999,
                            DeviceId = 4,
                            DiskUsage = 47.600000000000001,
                            MemoryUsage = 38.899999999999999,
                            RecordedAt = new DateTime(2024, 1, 4, 14, 20, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CPUUsage = 27.800000000000001,
                            DeviceId = 5,
                            DiskUsage = 46.299999999999997,
                            MemoryUsage = 37.200000000000003,
                            RecordedAt = new DateTime(2024, 1, 5, 16, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CPUUsage = 26.899999999999999,
                            DeviceId = 6,
                            DiskUsage = 45.0,
                            MemoryUsage = 36.100000000000001,
                            RecordedAt = new DateTime(2024, 1, 6, 8, 55, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CPUUsage = 29.5,
                            DeviceId = 7,
                            DiskUsage = 49.100000000000001,
                            MemoryUsage = 39.5,
                            RecordedAt = new DateTime(2024, 1, 7, 12, 35, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CPUUsage = 31.199999999999999,
                            DeviceId = 8,
                            DiskUsage = 50.700000000000003,
                            MemoryUsage = 41.799999999999997,
                            RecordedAt = new DateTime(2024, 1, 8, 13, 25, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CPUUsage = 24.100000000000001,
                            DeviceId = 9,
                            DiskUsage = 44.5,
                            MemoryUsage = 34.200000000000003,
                            RecordedAt = new DateTime(2024, 1, 9, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CPUUsage = 32.799999999999997,
                            DeviceId = 10,
                            DiskUsage = 51.899999999999999,
                            MemoryUsage = 43.700000000000003,
                            RecordedAt = new DateTime(2024, 1, 10, 17, 50, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CPUUsage = 30.5,
                            DeviceId = 11,
                            DiskUsage = 48.100000000000001,
                            MemoryUsage = 40.200000000000003,
                            RecordedAt = new DateTime(2024, 1, 11, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CPUUsage = 27.199999999999999,
                            DeviceId = 12,
                            DiskUsage = 45.600000000000001,
                            MemoryUsage = 36.899999999999999,
                            RecordedAt = new DateTime(2024, 1, 12, 14, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CPUUsage = 26.399999999999999,
                            DeviceId = 13,
                            DiskUsage = 44.299999999999997,
                            MemoryUsage = 35.700000000000003,
                            RecordedAt = new DateTime(2024, 1, 13, 9, 20, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CPUUsage = 28.899999999999999,
                            DeviceId = 14,
                            DiskUsage = 48.399999999999999,
                            MemoryUsage = 39.200000000000003,
                            RecordedAt = new DateTime(2024, 1, 14, 13, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            CPUUsage = 31.5,
                            DeviceId = 15,
                            DiskUsage = 50.100000000000001,
                            MemoryUsage = 42.700000000000003,
                            RecordedAt = new DateTime(2024, 1, 15, 16, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            CPUUsage = 23.800000000000001,
                            DeviceId = 16,
                            DiskUsage = 43.200000000000003,
                            MemoryUsage = 33.5,
                            RecordedAt = new DateTime(2024, 1, 16, 10, 20, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            CPUUsage = 25.899999999999999,
                            DeviceId = 17,
                            DiskUsage = 47.799999999999997,
                            MemoryUsage = 37.399999999999999,
                            RecordedAt = new DateTime(2024, 1, 17, 14, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            CPUUsage = 29.800000000000001,
                            DeviceId = 18,
                            DiskUsage = 50.899999999999999,
                            MemoryUsage = 41.5,
                            RecordedAt = new DateTime(2024, 1, 18, 15, 50, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            CPUUsage = 22.5,
                            DeviceId = 19,
                            DiskUsage = 42.700000000000003,
                            MemoryUsage = 32.100000000000001,
                            RecordedAt = new DateTime(2024, 1, 19, 11, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            CPUUsage = 24.899999999999999,
                            DeviceId = 20,
                            DiskUsage = 48.399999999999999,
                            MemoryUsage = 35.200000000000003,
                            RecordedAt = new DateTime(2024, 1, 20, 13, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            CPUUsage = 38.5,
                            DeviceId = 21,
                            DiskUsage = 55.100000000000001,
                            MemoryUsage = 46.700000000000003,
                            RecordedAt = new DateTime(2024, 1, 21, 9, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            CPUUsage = 27.800000000000001,
                            DeviceId = 22,
                            DiskUsage = 33.200000000000003,
                            MemoryUsage = 38.5,
                            RecordedAt = new DateTime(2024, 1, 22, 12, 55, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            CPUUsage = 39.899999999999999,
                            DeviceId = 23,
                            DiskUsage = 27.800000000000001,
                            MemoryUsage = 17.399999999999999,
                            RecordedAt = new DateTime(2024, 1, 23, 15, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            CPUUsage = 19.800000000000001,
                            DeviceId = 24,
                            DiskUsage = 30.899999999999999,
                            MemoryUsage = 61.5,
                            RecordedAt = new DateTime(2024, 1, 24, 11, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            CPUUsage = 25.800000000000001,
                            DeviceId = 25,
                            DiskUsage = 22.699999999999999,
                            MemoryUsage = 22.100000000000001,
                            RecordedAt = new DateTime(2024, 1, 25, 14, 20, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ViadexDashboard.Models.Compliance", b =>
                {
                    b.HasOne("ViadexDashboard.Models.Device", "Device")
                        .WithOne("Compliance")
                        .HasForeignKey("ViadexDashboard.Models.Compliance", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("ViadexDashboard.Models.DEXScore", b =>
                {
                    b.HasOne("ViadexDashboard.Models.Device", "Device")
                        .WithOne("DexScore")
                        .HasForeignKey("ViadexDashboard.Models.DEXScore", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("ViadexDashboard.Models.Sustainability", b =>
                {
                    b.HasOne("ViadexDashboard.Models.Device", "Device")
                        .WithOne("Sustainability")
                        .HasForeignKey("ViadexDashboard.Models.Sustainability", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("ViadexDashboard.Models.Telemetry", b =>
                {
                    b.HasOne("ViadexDashboard.Models.Device", "Device")
                        .WithMany("TelemetryData")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("ViadexDashboard.Models.Device", b =>
                {
                    b.Navigation("Compliance");

                    b.Navigation("DexScore");

                    b.Navigation("Sustainability");

                    b.Navigation("TelemetryData");
                });
#pragma warning restore 612, 618
        }
    }
}
